### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by sstaub** [ETCLabs/LuminosusEosEdition#1]
Hi Tim,
great software, but I can't open your website, tried it on safari (Mac OS and iOS) also on MS Edge.
On http://www.luminosus.org I get an "Apache2 Ubuntu Default Page" on https://....
![fehlermeldung](https://cloud.githubusercontent.com/assets/6450325/19183528/0f13fb9e-8c79-11e6-8291-f11b2ed67969.png)

Stefan Staub

**Comment by luminosuslight** [comment]
For the record, even if this is now 9 month old: it was a problem with IPv6 and should be fixed now.
