### ISSUE TITLE
[Feature] Fade Bank Page Size

### ISSUE THREAD

**Issue by ChristopherHaws** [ETCLabs/LuminosusEosEdition#22]
Hello,

Would it be possible to make it so that fader banks have a configurable size (count of faders)? This is possible with EOS via OSC by sending the command `/eos/fader/1/config/[page-size]`. This would be useful for using midi controllers such as the BCF2000 which only has 8 faders on it.

Thanks!

**Comment by luminosuslight** [comment]
Certainly it would be possible, but unfortunately I don't have the time at the moment to implement new features.
Pull requests are of course welcome though!

**Comment by luminosuslight** [comment]
This is included in #24.
